Setup primary and secondary yubikeys, and more systemd integration

diff --git a/emacs/dot-local/bin/emacsclient-x11 b/emacs/dot-local/bin/emacsclient-x11
--- a/emacs/dot-local/bin/emacsclient-x11
+++ b/emacs/dot-local/bin/emacsclient-x11
@@ -1,9 +1,9 @@
 #!/usr/bin/env sh
+set -eu
 
 if [ -z "${DISPLAY:-}" ]; then
-    printf '%s\n' \
-    'emacsclient-x11: DISPLAY is unset; invoking emacsclient without --display, so its default display-selection fallback will be used' >&2
-    exec /usr/bin/emacsclient "$@"
-else
-    exec /usr/bin/emacsclient --display="$DISPLAY" "$@"
+    printf '%s\n' 'emacsclient-x11: DISPLAY is unset; cannot create an X11 frame' >&2
+    exit 1
 fi
+
+exec /usr/bin/emacsclient --display="$DISPLAY" "$@"
